### ISSUE TITLE
No primary available for writes

### ISSUE THREAD

**Issue by luiscoms** [pyeve/eve#1011]
I have trouble on write in mongo cluster in `Eve 0.7.2`

On `Eve 0.6.4` works well but on I update this error occurs:

```
Traceback (most recent call last):
  File "/var/www/articles-api/env/lib/python3.4/site-packages/eve/methods/patch.py", line 205, in patch_internal
    resource, object_id, updates, original)
  File "/var/www/articles-api/env/lib/python3.4/site-packages/eve/io/mongo/mongo.py", line 538, in update
    return self._change_request(resource, id_, {"$set": updates}, original)
  File "/var/www/articles-api/env/lib/python3.4/site-packages/eve/io/mongo/mongo.py", line 474, in _change_request
    coll.update_one(filter_, changes)
  File "/var/www/articles-api/env/lib/python3.4/site-packages/pymongo/collection.py", line 890, in update_one
    with self._socket_for_writes() as sock_info:
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/var/www/articles-api/env/lib/python3.4/site-packages/pymongo/mongo_client.py", line 823, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/var/www/articles-api/env/lib/python3.4/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/var/www/articles-api/env/lib/python3.4/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: No primary available for writes
```

My connection string is like this:

`mongodb://articles:xxxx@10.155.32.110:27017,10.155.32.111:27017/articles?replicaSet=rs0&readPreference=nearest`

I also check this question but I guess that is not my case:

http://stackoverflow.com/questions/26091481/write-to-mongo-db-replica-set-take-care-of-primary-when-writing

pip freeze before update:

```
$ pip freeze
Eve==0.6.4
Flask==0.10.1
Flask-PyMongo==0.4.1
idna==2.1
itsdangerous==0.24
packaging==16.8
py==1.4.31
pyasn1==0.1.9
pycparser==2.14
PyJWT==1.4.0
pylint==1.4.4
pymongo==3.2.2
pyparsing==2.1.10
python-slugify==1.2.1
pytz==2016.3
PyYAML==3.12
requests==2.10.0
simplejson==3.8.2
six==1.10.0
tzlocal==1.2.2
Unidecode==0.4.20
urllib3==1.15.1
Werkzeug==0.11.3
wrapt==1.10.7
```

After update:

```
$ pip freeze
Eve==0.7.2
Flask==0.12
Flask-PyMongo==0.4.1
idna==2.5
itsdangerous==0.24
Jinja2==2.9.6
packaging==16.8
py==1.4.33
pyasn1==0.2.3
pycparser==2.17
PyJWT==1.4.2
pymongo==3.4.0
pyparsing==2.2.0
PyYAML==3.12
requests==2.11.1
simplejson==3.10.0
six==1.10.0
urllib3==1.20
Werkzeug==0.11.15
```

**Comment by nicolaiarocci** [comment]
Maybe this answer by Jesse, pymongo author, helps? http://stackoverflow.com/questions/40765581/pymongo-read-preferences-serverselectiontimeouterror-no-primary-available-for

**Comment by luiscoms** [comment]
I also checked this out and is not my case

**Comment by luiscoms** [comment]
@nicolaiarocci do you have other suggestion?
