### ISSUE TITLE
Query old dates

### ISSUE THREAD

**Issue by Kevin-Darty** [pyeve/eve#1110]
Hi,

My collection contains items with old dates like `"createdDate" : [ ISODate("1810-06-23T00:00:00Z") ] `.
When I try to get an item with an old date through `curl -i http://127.0.0.1:5000/myCollection/myId`, I have the following error: `ValueError: year=1810 is before 1900; the datetime strftime() methods require year >= 1900`

The used version:
```
pip show eve
Name: Eve
Version: 0.7.8
```

run.py:
```
#!/usr/bin/env python

from eve import Eve
app = Eve()

if __name__ == '__main__':
    app.run()
```

settings.py:
```
MONGO_HOST = 'localhost'
MONGO_PORT = 27017

MONGO_USERNAME = 'user'
MONGO_PASSWORD = 'pass'

MONGO_DBNAME = 'dbName'

SERVER_NAME = '127.0.0.1:5000'

RESOURCE_METHODS = ['GET', 'POST']

ITEM_METHODS = ['GET', 'PATCH', 'DELETE']

#CACHE_CONTROL = 'max-age=20'
#CACHE_EXPIRES = 20

ALLOW_UNKNOWN = True

DOMAIN = {
        'myCollection': {},
        'otherCollection': {}
}
```

The trace:
```
127.0.0.1 - - [08/Feb/2018 00:36:30] "GET /myCollection/myId HTTP/1.1" 404 -
[2018-02-08 00:36:36,864] ERROR in app: Exception on /myCollection/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/eve/endpoints.py", line 63, in collections_endpoint
    return send_response(resource, response)
  File "/usr/local/lib/python2.7/dist-packages/eve/render.py", line 57, in decorated
    r = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eve/render.py", line 96, in send_response
    return _prepare_response(resource, *response if response else [None])
  File "/usr/local/lib/python2.7/dist-packages/eve/render.py", line 150, in _prepare_response
    rendered = globals()[renderer](dct)
  File "/usr/local/lib/python2.7/dist-packages/eve/render.py", line 303, in render_json
    sort_keys=config.JSON_SORT_KEYS)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 291, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/encoder.py", line 373, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/eve/io/mongo/mongo.py", line 57, in default
    return super(MongoJSONEncoder, self).default(obj)
  File "/usr/local/lib/python2.7/dist-packages/eve/io/base.py", line 28, in default
    return date_to_str(obj)
  File "/usr/local/lib/python2.7/dist-packages/eve/utils.py", line 209, in date_to_str
    return datetime.strftime(date, config.DATE_FORMAT) if date else None
ValueError: year=1810 is before 1900; the datetime strftime() methods require year >= 1900
```

**Comment by nicolaiarocci** [comment]
I am probably stating the obvious, but I am afraid that is a limitation of [python's `strftime()`](https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior):

    Regardless of platform, years before 1900 cannot be used.

A possible workaround might be to play with `isoformat`, see [this](https://stackoverflow.com/questions/10263956/use-datetime-strftime-on-years-before-1900-require-year-1900) answer on SO for example. Feel free to submit a PR if you feel like doing it.

**Comment by nicolaiarocci** [comment]
I should add that if you're on Python 3.3+ this should not be a issue.

**Comment by nicolaiarocci** [comment]
Closing this as it is a non-issue in Python 3.3+, and seems a very marginal use-case anyways. We're going to drop Python 2 before Eve 1.0 is released.
