### ISSUE TITLE
Inconsistent dependencies

### ISSUE THREAD

**Issue by mohierf** [pyeve/eve#1111]
The *setup.py* requires:
```
install_requires = [
    'cerberus>=1.1',
    'events>=0.3,<0.4',
    'simplejson>=3.3.0,<4.0',
    'werkzeug>=0.9.4,<=0.11.15',
    'markupsafe>=0.23,<1.0',
    'jinja2>=2.8,<3.0',
    'itsdangerous>=0.24,<1.0',
    'flask>=0.10.1,<=0.12',
    'pymongo>=3.5',
]
```` 

whereas the *requirements.txt* is:
```
Cerberus==1.1
Events==0.3
Flask==0.12
itsdangerous==0.24
Jinja2==2.9.4
MarkupSafe==0.23
pymongo==3.5.0
simplejson==3.8.2
Werkzeug==0.11.15
```

The current Flask version is 0.12.2 and it is not compatible with Eve which raises an exception when it is installed:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/bin/alignak-backend", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'flask<=0.12,>=0.10.1' distribution was not found and is required by Eve
```

The problem is that some Eve relaed packages do not set an hard dependency on a specific version (eg. flask-apscheduler or flask-bootstrap) and it installs the 0.12.2 Flask version that is not compatible.

It may be possible to allow using Flask 0.12.2 ?

**Comment by nicolaiarocci** [comment]
Yes, this needs a fix. Thanks for reporting.
