### ISSUE TITLE
Eve with uWSGI must be started with root level privileges

### ISSUE THREAD

**Issue by mohierf** [pyeve/eve#1113]
Running Eve with uWSGI and a non-root user account raises an error that breaks the application.
```
Alignak backend uWSGI configuration file: /root/git/Smoove/smoove/etc/alignak-backend/uwsgi.ini
Alignak backend configuration file: /root/git/Smoove/smoove/etc/alignak-backend/settings.json
[uWSGI] getting INI configuration from /root/git/Smoove/smoove/etc/alignak-backend/uwsgi.ini
*** Starting uWSGI 2.0.16 (64bit) on [Fri Feb 16 16:04:25 2018] ***
compiled with version: 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347) on 16 February 2018 12:59:22
os: FreeBSD-11.1-RELEASE-p1 FreeBSD 11.1-RELEASE-p1 #0: Wed Aug  9 11:55:48 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
nodename: alignak_new
machine: amd64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /root/git/alignak-backend
writing pidfile to /tmp/alignak-backend.pid
detected binary path: /usr/local/bin/uwsgi
dropping root privileges as early as possible
setuid() to 1001
your processes number limit is 234770
your memory page size is 4096 bytes
detected max file descriptor number: 469539
lock engine: POSIX semaphores
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5000 fd 3
dropping root privileges after socket binding
Python version: 2.7.14 (default, Feb 13 2018, 15:26:49)  [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]
Python main interpreter initialized at 0x803c7d000
dropping root privileges after plugin initialization
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 914184 bytes (892 KB) for 8 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./alignak_backend/app.py", line 32, in <module>
    from eve import Eve
  File "/usr/local/lib/python2.7/site-packages/Eve-0.7.8-py2.7.egg/eve/__init__.py", line 87, in <module>
    from eve.flaskapp import Eve  # noqa
  File "/usr/local/lib/python2.7/site-packages/Eve-0.7.8-py2.7.egg/eve/flaskapp.py", line 24, in <module>
    from eve.endpoints import collections_endpoint, item_endpoint, home_endpoint, \
  File "/usr/local/lib/python2.7/site-packages/Eve-0.7.8-py2.7.egg/eve/endpoints.py", line 14, in <module>
    from bson import tz_util
  File "build/bdist.freebsd-11.1-RELEASE-p1-amd64/egg/bson/__init__.py", line 107, in <module>
  File "build/bdist.freebsd-11.1-RELEASE-p1-amd64/egg/bson/_cbson.py", line 7, in <module>
  File "build/bdist.freebsd-11.1-RELEASE-p1-amd64/egg/bson/_cbson.py", line 4, in __bootstrap__
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1226, in resource_filename
    self, resource_name
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1729, in get_resource_filename
    self._extract_resource(manager, self._eager_to_zip(name))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1759, in _extract_resource
    self.egg_name, self._parts(zip_path)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1293, in get_cache_path
    self.extraction_error()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1273, in extraction_error
    raise err
pkg_resources.ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s)
to the Python egg cache:

  [Errno 13] Permission denied: '/root/.cache/Python-Eggs'

The Python egg cache directory is currently set to:

  /root/.cache/Python-Eggs

Perhaps your account does not have write access to this directory?
You can change the cache directory by setting the PYTHON_EGG_CACHE
environment variable to point to an accessible directory.

unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
dropping root privileges after application loading
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 58709)
spawned uWSGI worker 1 (pid: 58714, cores: 1)
spawned uWSGI worker 2 (pid: 58715, cores: 1)
spawned uWSGI worker 3 (pid: 58716, cores: 1)
spawned uWSGI worker 4 (pid: 58717, cores: 1)
spawned uWSGI worker 5 (pid: 58718, cores: 1)
spawned uWSGI worker 6 (pid: 58719, cores: 1)
spawned uWSGI worker 7 (pid: 58720, cores: 1)
spawned uWSGI worker 8 (pid: 58721, cores: 1)
```

My uWSGI configuration file:
```
[uwsgi]
http-socket = 0.0.0.0:5000

# Uncomment if you installed from distribution packaging
# plugin = python
# Uncomment if you installed from distribution packaging
# plugin = logfile

# Python module
module = alignak_backend.app:app

enable-threads = true
processes = 8

# Log requests activity (disable by default because too verbose)
# req-logger = file:/usr/local/var/log/alignak-backend/backend-access.log
# Log information, errors...
;logger = file:/usr/var/log/alignak-backend/backend-error.log

# Report memory activity to the stats
memory-report = true

# Define specific uid/gid if uWSGI started as root
uid = alignak
guid = alignak

# Default buffer size for HTTP header is very low (4096)
buffer-size = 32768

# uWSGI master process: use a master process and store its pid
master = true
pidfile = /tmp/alignak-backend.pid

# ---
# Statistics part
# Uncomment this line to activate statistics sending to carbon/graphite
# carbon =  127.0.0.1:2003
# defaults to uwsgi
carbon-root = alignak-backend
# replace dots in hostnames
carbon-hostname-dots = -
```

The application starts correctly if I comment the `user` and `group` variables ... but then my application runs with root level privileges :/

**note** that with former Eve versions I did not have this problem

**Comment by nicolaiarocci** [comment]
hmm I do not think this has anythong to do with Eve itsef?
