### ISSUE TITLE
error for python3.6 SystemError: Parent module 'config' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by Jiangshan00001** [pyeve/eve#1135]
C:\Python36-32\python.exe F:/PROGRAM/inovafitness/source/PC/inova_cloud_jngrid/programs/api/mysql_api/mysql_api.py
Traceback (most recent call last):
  File "F:/PROGRAM/inovafitness/source/PC/inova_cloud_jngrid/programs/api/mysql_api/mysql_api.py", line 7, in <module>
    app = Eve()
  File "C:\Python36-32\lib\site-packages\eve\flaskapp.py", line 139, in __init__
    self.load_config()
  File "C:\Python36-32\lib\site-packages\eve\flaskapp.py", line 255, in load_config
    self.config.from_pyfile(pyfile)
  File "C:\Python36-32\lib\site-packages\flask\config.py", line 130, in from_pyfile
    exec(compile(config_file.read(), filename, 'exec'), d.__dict__)
  File "C:\Python36-32\lib\site-packages\isort\settings.py", line 34, in <module>
    from .pie_slice import itemsview, lru_cache, native_str
SystemError: Parent module 'config' not loaded, cannot perform relative import

**Comment by nicolaiarocci** [comment]
Are you useing eve-sqlalchemy? If so, you should eventually open a ticket on that extension's repository.

**Comment by Lextum** [comment]
@Jiangshan00001 Did you find a soution to the problem? I am using Python 3.8 and even the a simple example script from the website fails with this error.

**Comment by Jiangshan00001** [comment]
I didn't find a solution.
upgrade the python may be help.
