### ISSUE TITLE
Internal error with embedded None field

### ISSUE THREAD

**Issue by gwainer** [pyeve/eve#1170]
I believe I've stumbled in an issue when getting second-level embedded documents if the first level is None.

### Expected Behavior
Considering the schemas below:

```python
device_schema = {
    'site': {
        'type': 'objectid',
        'data_relation': {
            'resource': 'sites',
            'field': '_id',
            'embeddable': True
        },
        'nullable': True,
    },
},
site_schema = {
    'employees': {
        'type': 'list',
        'schema': {
            'type': 'objectid',
            'required': True,
            'data_relation': {
                'resource': 'employees',
                'field': '_id',
                'embeddable': True
            },
        }
    },
}
```

`device` has an embedded `site` inside, `site` has a list of `employees`. When `device.site` is None, since it is `nullable`, if you set embedded documents as `embedded={"site": 1, "site.employees": 1}`, an internal error occurs.

### Actual Behavior

We have an internal error, and it cannot be avoid by pre_get event hooks, since request cannot be altered inside hooks. Traceback:

```python
Traceback (most recent call last):
  File "/eve/lib/python3.5/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "/eve/lib/python3.5/site-packages/gevent/pywsgi.py", line 908, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/eve/lib/python3.5/site-packages/eve/flaskapp.py", line 1043, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/eve/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/eve/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/eve/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/eve/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/eve/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/eve/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/eve/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/eve/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/eve/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/eve/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/eve/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/eve/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/eve/lib/python3.5/site-packages/eve/endpoints.py", line 94, in item_endpoint
    response = getitem(resource, **lookup)
  File "/eve/lib/python3.5/site-packages/eve/methods/common.py", line 297, in rate_limited
    return f(*args, **kwargs)
  File "/eve/lib/python3.5/site-packages/eve/auth.py", line 78, in decorated
    return f(*args, **kwargs)
  File "/eve/lib/python3.5/site-packages/eve/methods/common.py", line 1181, in decorated
    r = f(resource, **combined_args)
  File "/eve/lib/python3.5/site-packages/eve/methods/get.py", line 261, in getitem
    return getitem_internal(resource, **lookup)
  File "/eve/lib/python3.5/site-packages/eve/methods/get.py", line 351, in getitem_internal
    build_response_document(document, resource, embedded_fields, latest_doc)
  File "/eve/lib/python3.5/site-packages/eve/methods/common.py", line 612, in build_response_document
    resolve_embedded_documents(document, resource, embedded_fields)
  File "/eve/lib/python3.5/site-packages/eve/methods/common.py", line 934, in resolve_embedded_documents
    if last_field not in subdocument:
TypeError: argument of type 'NoneType' is not iterable
```

### Environment

* Python version: 3.5
* Eve version: 0.8

**Comment by nicolaiarocci** [comment]
Hi, on Eve 0.8.1-dev the following test passes:

```py
    def test_triage_issue_1170(self):
        self.app.register_resource(
            "devices", {
                "schema": {
                    'site': {
                        'type': 'objectid',
                        'data_relation': {
                            'resource': 'sites',
                            'field': '_id',
                            'embeddable': True
                        },
                        'nullable': True, }}})
        self.app.register_resource(
            "sites", {
                "schema": {
                    'employees': {
                        'type': 'list',
                        'schema': {
                            'type': 'objectid',
                            'required': True,
                            'data_relation': {
                                'resource': 'employees',
                                'field': '_id',
                                'embeddable': True
                        }}}}})

        data = {"site": None}
        r, status = self.post("devices", data=data)
        self.assert201(status)

        raw_r = self.test_client.get('devices?embedded={"site":1,"sites.employees": 1}')
        self.assert200(raw_r.status_code)
```

Is there anything more I need to do in order to reproduce the ticket? Or maybe you can verify if this is still an issue with v0.8.1-dev?

**Comment by gwainer** [comment]
It works OK now. Thank you for the fix.
