### ISSUE TITLE
Test failure on master branch

### ISSUE THREAD

**Issue by jsolbrig** [pyeve/eve#1193]
I'm attempting to prepare a pull request, but have discovered that one of the unit tests fails even on an unmodifed checkout of the master branch.  Only one of the tests is failing and I am at a loss for how to fix it.  Everything else passes without issue.  Can anyone else reproduce this issue?

### Expected Behavior

All tests should pass.

### Actual Behavior

Test `eve.tests.methods.post.TestPost.test_post_decimal_number_success` fails for all versions of Python using both `tox` and `unittest`.

```pytb
$ python3 -m unittest -q eve.tests.methods.post.TestPost.test_post_decimal_number_success
/home/jsolbrig/eve/eve/methods/get.py:236: DeprecationWarning: count is deprecated. Use Collection.count_documents instead.
  count = cursor.count(with_limit_and_skip=False)
[2018-09-20 18:15:03,947] ERROR in app: Exception on /invoices/ [POST]
Traceback (most recent call last):
  File "/build/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/build/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/build/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/build/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/build/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/build/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jsolbrig/eve/eve/endpoints.py", line 58, in collections_endpoint
    response = post(resource)
  File "/home/jsolbrig/eve/eve/methods/common.py", line 317, in rate_limited
    return f(*args, **kwargs)
  File "/home/jsolbrig/eve/eve/auth.py", line 80, in decorated
    return f(*args, **kwargs)
  File "/home/jsolbrig/eve/eve/methods/common.py", line 1251, in decorated
    r = f(resource, **combined_args)
  File "/home/jsolbrig/eve/eve/methods/post.py", line 49, in post
    return post_internal(resource, payl, skip_validation=False)
  File "/home/jsolbrig/eve/eve/methods/post.py", line 260, in post_internal
    ids = app.data.insert(resource, documents)
  File "/home/jsolbrig/eve/eve/io/mongo/mongo.py", line 459, in insert
    return coll.insert_many(doc_or_docs, ordered=True).inserted_ids
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/collection.py", line 753, in insert_many
    blk.execute(write_concern, session=session)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/bulk.py", line 513, in execute
    return self.execute_command(generator, write_concern, session)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/bulk.py", line 338, in execute_command
    self.is_retryable, retryable_bulk, s, self)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1196, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/bulk.py", line 333, in retryable_bulk
    retryable, full_result)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/bulk.py", line 288, in _execute_command
    result = bwc.write_command(request_id, msg, to_send)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/message.py", line 920, in write_command
    reply = self.sock_info.write_command(request_id, msg)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 651, in write_command
    reply = self.receive_message(request_id)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 612, in receive_message
    self._raise_connection_failure(error)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 745, in _raise_connection_failure
    raise error
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 610, in receive_message
    self.max_message_size)
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 173, in receive_message
    _receive_data_on_socket(sock, 16))
  File "/build/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 238, in _receive_data_on_socket
    raise AutoReconnect("connection closed")
pymongo.errors.AutoReconnect: connection closed
======================================================================
FAIL: test_post_decimal_number_success (eve.tests.methods.post.TestPost)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jsolbrig/eve/eve/tests/methods/post.py", line 335, in test_post_decimal_number_success
    self.assert201(status)
  File "/home/jsolbrig/eve/eve/tests/__init__.py", line 106, in assert201
    self.assertEqual(status, 201)
AssertionError: 500 != 201

----------------------------------------------------------------------
Ran 1 test in 0.216s

FAILED (failures=1)
```

### Environment

* Python version: 2.7.15, 3.4.9, 3.5.6, 3.6.6, pypy
* Eve version: 0.8.1.dev0 (current master branch)

**Comment by jsolbrig** [comment]
After submitting a pull request, it appears that this does not fail in Travis CI.  The pull request passed all tests.

**Comment by nicolaiarocci** [comment]
What happens if you run the tests with tox? I assume there might be some dependency/versioning issue on your end? Because tests are passing on CI, I am closing the ticket for the time being.
