### ISSUE TITLE
Unauthorized Exception from Werkzeug 0.15.4 causes 500 errors

### ISSUE THREAD

**Issue by spbrien** [pyeve/eve#1272]
Some version of this issue: https://github.com/pyeve/eve/issues/1245 seems to be happening again in the latest version of Werkzeug (0.15.4). I have no problems if I pin Werkzeug to version 0.15.1

---

### Expected Behavior

Unauthorized requests receive a 401 Response

### Actual Behavior

500 Error

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/eve/endpoints.py", line 58, in collections_endpoint
    response = post(resource)
  File "/usr/local/lib/python3.7/site-packages/eve/methods/common.py", line 318, in rate_limited
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/eve/auth.py", line 79, in decorated
    return auth.authenticate()
  File "/usr/local/lib/python3.7/site-packages/eve/auth.py", line 152, in authenticate
    ("WWW-Authenticate", 'Basic realm="%s"' % __package__),
  File "/usr/local/lib/python3.7/site-packages/werkzeug/exceptions.py", line 762, in abort
    return _aborter(status, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/exceptions.py", line 743, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Unauthorized: 401 Unauthorized: Please provide proper credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.7/site-packages/eve/flaskapp.py", line 1105, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1732, in handle_user_exception
    return self.handle_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1661, in handle_http_exception
    return handler(e)
  File "/usr/local/lib/python3.7/site-packages/eve/endpoints.py", line 182, in error_endpoint
    return send_response(None, (response, None, None, error.code, headers))
  File "/usr/local/lib/python3.7/site-packages/eve/render.py", line 52, in decorated
    r = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/eve/render.py", line 92, in send_response
    return _prepare_response(resource, *response if response else [None])
  File "/usr/local/lib/python3.7/site-packages/eve/render.py", line 164, in _prepare_response
    for header, value in headers:
TypeError: cannot unpack non-iterable NoneType object
/usr/local/lib/python3.7/site-packages/cerberus/validator.py:1609: UserWarning: No validation schema is defined for the arguments of rule '_metadata'
  "'%s'" % method_name.split('_', 2)[-1]
```

### Environment

* Python version: 3.6.4
* Eve version: 0.9

**Comment by nicolaiarocci** [comment]
This looks similar to #1267. Can you please check if current `master` works for you?

**Comment by spbrien** [comment]
@nicolaiarocci I believe you're correct, `master` works for me. Thanks!
