### ISSUE TITLE
First example of Eve use doesn't work

### ISSUE THREAD

**Issue by sybrenstuvel** [pyeve/eve#1277]
### Expected Behavior

This should work, as it's [the very first example of how Eve works](https://docs.python-eve.org/en/stable/#eve-is-simple):

```python
from eve import Eve

app = Eve()
```

### Actual Behavior

```pytb
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from eve import Eve
>>> app = Eve()
Traceback (most recent call last):
  File "/home/sybren/workspace/cloud/eve/eve/flaskapp.py", line 319, in validate_domain_struct
    domain = self.config["DOMAIN"]
KeyError: 'DOMAIN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sybren/workspace/cloud/eve/eve/flaskapp.py", line 161, in __init__
    self.validate_domain_struct()
  File "/home/sybren/workspace/cloud/eve/eve/flaskapp.py", line 321, in validate_domain_struct
    raise ConfigException("DOMAIN dictionary missing or wrong.")
eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.
```

### Environment

* Python version: 3.6.7
* Eve version: 0.9.1

**Comment by nicolaiarocci** [comment]
![image](https://user-images.githubusercontent.com/512968/58812503-4ff55900-8622-11e9-8698-049b7a69fc57.png)

**Comment by nicolaiarocci** [comment]
Oh, wow .This must have been around since, like, forever. I can only imagine how many people scared away from the project. Thanks for reporting.
