### ISSUE TITLE
The server do not return response for example from docs

### ISSUE THREAD

**Issue by yarfuo** [pyeve/eve#1305]
### Expected Behavior

I want to receive error or something else. **Errors should never pass silently**. I think this is due to an unconfigured database.

#### Steps to reproduce

- ./run.py
```python
from eve import Eve
eve = Eve()
eve.run()
```
- ./settings.py
```python
DOMAIN = {'people': {}}
```
```bash
$ pipenv install eve
$ python run.py
$ http 127.0.0.1:5000/people
```

### Actual Behavior

The server doesn't respond.
[![asciicast](https://asciinema.org/a/UUKuImf1O535sXtbSTeeYCVpo.svg)](https://asciinema.org/a/UUKuImf1O535sXtbSTeeYCVpo)
### Environment

* Python version: 3.6.8
* Eve version: 0.9.2

**Comment by nicolaiarocci** [comment]
If you wait a (good) while, eventually you will get the connection error when it times out.

```
❯ python run.py    
 * Serving Flask app "eve" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2019-12-18 10:28:31,039] ERROR in app: Exception on /people [GET]
Traceback (most recent call last):
  File "/home/nicola/dev/pyeve/eve/eve/io/mongo/mongo.py", line 273, in find
    count = target.count_documents(spec)
  File "/home/nicola/.virtualenvs/eve/lib/python3.8/site-packages/pymongo/collection.py", line 1683, in count_documents
    with self._socket_for_reads(session) as (sock_info, slave_ok):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/nicola/.virtualenvs/eve/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1099, in _socket_for_reads
    server = topology.select_server(read_preference)
  File "/home/nicola/.virtualenvs/eve/lib/python3.8/site-packages/pymongo/topology.py", line 222, in select_server
    return random.choice(self.select_servers(selector,
  File "/home/nicola/.virtualenvs/eve/lib/python3.8/site-packages/pymongo/topology.py", line 182, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/home/nicola/.virtualenvs/eve/lib/python3.8/site-packages/pymongo/topology.py", line 198, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```
I am guessing you are running on some serverless environment or similar, where the process is archived/disposed before the timeout occurs.
