### ISSUE TITLE
By not using mongo for data storage eve tries to connect to mongo - 500

### ISSUE THREAD

**Issue by markross42** [pyeve/eve#1307]
stared using eve, tried basic example

```python
from eve import Eve

settings = {'DOMAIN': {'people': {}}}

app = Eve(settings=settings)
app.run()
```

### Actual Behavior

HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Type: text/html
Content-Length: 290
Server: Eve/0.9.2 Werkzeug/0.15.4 Python/3.7.3
Date: Wed, 04 Sep 2019 19:46:23 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/eve/endpoints.py", line 56, in collections_endpoint
    response = get(resource, lookup)
  File "/usr/local/lib/python3.7/site-packages/eve/methods/common.py", line 318, in rate_limited
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/eve/auth.py", line 80, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/eve/methods/common.py", line 1354, in decorated
    r = f(resource, **combined_args)
  File "/usr/local/lib/python3.7/site-packages/eve/methods/get.py", line 51, in get
    return get_internal(resource, **lookup)
  File "/usr/local/lib/python3.7/site-packages/eve/methods/get.py", line 125, in get_internal
    return _perform_find(resource, lookup)
  File "/usr/local/lib/python3.7/site-packages/eve/methods/get.py", line 266, in _perform_find
    resource, req, lookup, perform_count=not config.OPTIMIZE_PAGINATION_FOR_SPEED
  File "/usr/local/lib/python3.7/site-packages/eve/io/mongo/mongo.py", line 287, in find
    count = target.count()
  File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 1800, in count
    return self._count(cmd, collation, session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 1600, in _count
    _cmd, self._read_preference_for(session), session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1455, in _retryable_read
    read_pref, session, address=address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1254, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 231, in select_server
    address))
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 189, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
127.0.0.1 - - [04/Sep/2019 21:46:23] "GET /people HTTP/1.1" 500 -
```

### Environment

* Python version: python3.7
* Eve version: Eve-0.9.2

**Comment by nicolaiarocci** [comment]
this is excpected, as eve needs to connect to the database in order to provide the requested data.
