### ISSUE TITLE
'query_objectid_as_string' causes error

### ISSUE THREAD

**Issue by pi-null-mezon** [pyeve/eve#1370]
I want to filter (?where=) my /users by 'uuid'. So, after some googling I have come to [this](https://stackoverflow.com/questions/38627492/python-eve-where-query-returns-empty-result) solution. But after adding **'query_objectid_as_string': True** to validation scheme I can not POST anything to /users endpoint (

### Expected Behavior

Add new users (with filtering support) to database with following schema:

```python
user_schema = {
    'uuid': { 
       'query_objectid_as_string': True,
       'type': 'string',
       'minlength': 1,
       'maxlength': 100,
       'unique': True
    }
}
```

### Actual Behavior

On POST I see error in console:
```
cerberus.schema.SchemaError: {'uuid': [{'query_objectid_as_string': ['unknown rule']}]}
```

Full traceback:
```pytb
Traceback (most recent call last):
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/endpoints.py", line 58, in collections_endpoint
    response = post(resource)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/methods/common.py", line 318, in rate_limited
    return f(*args, **kwargs)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/auth.py", line 80, in decorated
    return f(*args, **kwargs)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/methods/common.py", line 1356, in decorated
    r = f(resource, **combined_args)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/methods/post.py", line 49, in post
    return post_internal(resource, payl, skip_validation=False)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/methods/post.py", line 167, in post_internal
    schema, resource=resource, allow_unknown=resource_def["allow_unknown"]
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/validation.py", line 29, in __init__
    super(Validator, self).__init__(*args, **kwargs)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/validator.py", line 181, in __init__
    self.schema = kwargs.get('schema', None)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/validator.py", line 562, in schema
    self._schema = DefinitionSchema(self, schema)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/schema.py", line 82, in __init__
    self.validate(schema)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/schema.py", line 262, in validate
    self._validate(schema)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/schema.py", line 278, in _validate
    raise SchemaError(self.schema_validator.errors)
cerberus.schema.SchemaError: {'uuid': [{'query_objectid_as_string': ['unknown rule']}]}
ERROR:eve:Exception on /users [POST]
Traceback (most recent call last):
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/endpoints.py", line 58, in collections_endpoint
    response = post(resource)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/methods/common.py", line 318, in rate_limited
    return f(*args, **kwargs)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/auth.py", line 80, in decorated
    return f(*args, **kwargs)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/methods/common.py", line 1356, in decorated
    r = f(resource, **combined_args)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/methods/post.py", line 49, in post
    return post_internal(resource, payl, skip_validation=False)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/methods/post.py", line 167, in post_internal
    schema, resource=resource, allow_unknown=resource_def["allow_unknown"]
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/eve/validation.py", line 29, in __init__
    super(Validator, self).__init__(*args, **kwargs)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/validator.py", line 181, in __init__
    self.schema = kwargs.get('schema', None)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/validator.py", line 562, in schema
    self._schema = DefinitionSchema(self, schema)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/schema.py", line 82, in __init__
    self.validate(schema)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/schema.py", line 262, in validate
    self._validate(schema)
  File "/home/alex/Programming/Drivercontrol/Eve/venv/lib/python3.6/site-packages/cerberus/schema.py", line 278, in _validate
    raise SchemaError(self.schema_validator.errors)
cerberus.schema.SchemaError: {'uuid': [{'query_objectid_as_string': ['unknown rule']}]}

```

### Environment
* Linux Ubuntu 18.04x64
* Python 3.6
* Eve 1.1, Cerberus 1.3.2

**Comment by pi-null-mezon** [comment]
Sorry, my mistake. *query_objectid_as_string* should goes to domain, not validation schema
