### ISSUE TITLE
Can we use media type field in nested document?

### ISSUE THREAD

**Issue by earthwoo** [pyeve/eve#1409]
Hi, can we use media type field in embedded document?

### Expected Behavior

if I define schema as:

```python
accounts = {
    'name': {'type': 'string'},
    'pic': {'type': 'media'},
    ...
}
```
then I can post or patch a file to pic field. But when I define schema as:
```python
accounts = {
    'name': {'type': 'string'},
    'info':{"type":"dict",
         "schema": {
               pic:{'type': 'media'},
              ...
        }
}
```
post or patch a file to info.pic will return error:
```json
{
    "_error": {
        "code": 400,  
        "message": "An exception occurred: cannot encode object: <FileStorage: 'pic.png' ('image/png')>, of type: <class 'werkzeug.datastructures.FileStorage'>"
    },
    "_status": "ERR"
}
```

### Actual Behavior

Can use media type in embedded document?

```pytb
Traceback (most recent call last):
File "/srv/wms/backend/lib64/python3.5/site-packages/eve/methods/patch.py", line 223, in patch_internal
app.data.update(resource, object_id, updates, original)
File "/srv/wms/backend/lib64/python3.5/site-packages/eve/io/mongo/mongo.py", line 595, in update
return self._change_request(resource, id_, {"$set": updates}, original)
File "/srv/wms/backend/lib64/python3.5/site-packages/eve/io/mongo/mongo.py", line 518, in _change_request
else coll.update_one(filter_, changes)
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/collection.py", line 1002, in update_one
session=session),
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/collection.py", line 858, in _update_retryable
_update, session)
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/mongo_client.py", line 1280, in _retryable_write
return self._retry_with_session(retryable, func, s, None)
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/mongo_client.py", line 1233, in _retry_with_session
return func(session, sock_info, retryable)
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/collection.py", line 854, in _update
retryable_write=retryable_write)
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/collection.py", line 824, in _update
retryable_write=retryable_write).copy()
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/pool.py", line 589, in command
self._raise_connection_failure(error)
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/pool.py", line 750, in _raise_connection_failure
raise error
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/pool.py", line 584, in command
user_fields=user_fields)
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/network.py", line 121, in command
codec_options, ctx=compression_ctx)
File "/srv/wms/backend/lib64/python3.5/site-packages/pymongo/message.py", line 678, in _op_msg
flags, command, identifier, docs, check_keys, opts)
bson.errors.InvalidDocument: cannot encode object: <FileStorage: 'pic.png' ('image/png')>, of type: <class 'werkzeug.datastructures.FileStorage'>
```

### Environment

* Python version: 3.5
* Eve version: 1.1.1

**Comment by earthwoo** [comment]
Sorry, "embedded document" is wrong,  should be 'nested document'.
