### ISSUE TITLE
Token authorization 

### ISSUE THREAD

**Issue by ernests** [pyeve/eve#1436]
### Expected Behavior

I'm implementing Token authorization from example https://docs.python-eve.org/en/stable/authentication.html. It works if I provide valid token but it returns 500 Internal server error when there is no token provided. 
Wanted to handle it and return 401. 
How to do it properly? 

Code:
```
class RolesAuth(TokenAuth):
    def check_auth(self, token, allowed_roles, resource, method):
         # use Eve's own db driver; no additional connections/resources are used
         accounts = app.data.driver.db['accounts']
         lookup = {'token': token}
         if allowed_roles:
             # only retrieve a user if his roles match ``allowed_roles``
             lookup['roles'] = {'$in': allowed_roles}
         account = accounts.find_one(lookup)
         return account
```
## Traceback
```
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File ".../lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".../lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File ".../lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File ".../lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File ".../lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".../lib/python3.6/site-packages/eve/methods/common.py", line 325, in rate_limited
    return f(*args, **kwargs)
  File ".../lib/python3.6/site-packages/eve/auth.py", line 79, in decorated
    return auth.authenticate()
  File ".../lib/python3.6/site-packages/eve/auth.py", line 152, in authenticate
    www_authenticate=("WWW-Authenticate", 'Basic realm="%s"' % __package__),
  File ".../lib/python3.6/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File ".../lib/python3.6/site-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'www_authenticate'
```

**Comment by ernests** [comment]
Launched it with gunicorn on nginx server and now endpoint requires login credentials. I assume it is expected behaviour and error above appears with development server. Case closed.
