### ISSUE TITLE
Sorting does and doesn't work

### ISSUE THREAD

**Issue by dmitry-saritasa** [pyeve/eve#496]
Hi Guys,

this does work
http://localhost:5000/people?sort=[("lastname",-1)]

this doesn't
http://localhost:5000/people?sort=-lastname

per documentation this format is supported, but when called get this:
http://python-eve.org/features.html

File "C:\Programming\Python275\lib\site-packages\eve\methods\common.py", line 675, in decorated
r = f(resource, **combined_args)
File "C:\Programming\Python275\lib\site-packages\eve\methods\get.py", line 113, in get
cursor = app.data.find(resource, req, lookup)
File "C:\Programming\Python275\lib\site-packages\eve\io\mongo\mongo.py", line 146, in find
client_sort = ast.literal_eval(req.sort)
File "C:\Programming\Python275\lib\ast.py", line 80, in literal_eval
Display the sourcecode for this frameOpen an interactive python shell in this framereturn _convert(node_or_string)
File "C:\Programming\Python275\lib\ast.py", line 79, in _convert
raise ValueError('malformed string')
ValueError: malformed string

below is my settings.py file

MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DBNAME = 'apitest'
DEBUG = True
SORTING = True

schema = {
    '_id': {
        'type': 'integer'
    },
    'firstname': {
        'type': 'string',
        'minlength': 1,
        'maxlength': 10,
    },
    'lastname': {
        'type': 'string',
        'minlength': 1,
        'maxlength': 15,
        'required': True,
        'unique': True,
    },
    'role': {
        'type': 'list',
        'allowed': ["author", "contributor", "copy"],
    },
    'location': {
        'type': 'dict',
        'schema': {
            'address': {'type': 'string'},
            'city': {'type': 'string'}
        },
    },
    'born': {
        'type': 'datetime',
    },
}

people = {
    'item_title': 'person',

```
'additional_lookup': {
    'url': 'regex("[\w]+")',
    'field': 'lastname'
},

'cache_control': 'max-age=10,must-revalidate',
'cache_expires': 10,

'resource_methods': ['GET', 'POST'],
'datasource': {
    'default_sort': [('lastname', -1)],
    'filter': {'lastname': {'$exists': True}}

},
'schema': schema
```

}

DOMAIN = {
    'people': people,
}

RESOURCE_METHODS = ['GET', 'POST', 'DELETE']
ITEM_METHODS = ['GET', 'PATCH', 'PUT', 'DELETE']

**Comment by NagarajGond** [comment]
Hi,

Below expression doesn't work when I tried eve with eve_sqlalchemy for MySQL.
http://127.0.0.1:5001/activity?where={"status":"Ok"}

but this works: http://127.0.0.1:5001/activity?where=status==Ok


Name: Eve
Version: 0.6.4

Name: SQLAlchemy
Version: 1.1.4

Name: Eve-SQLAlchemy
Version: 0.4.1


'''
-->
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/eve/flaskapp.py", line 968, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.6/site-packages/eve/endpoints.py", line 54, in collections_endpoint
    response = get(resource, lookup)
  File "/usr/lib/python2.6/site-packages/eve/methods/common.py", line 242, in rate_limited
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/eve/auth.py", line 79, in decorated
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/eve/methods/common.py", line 949, in decorated
    r = f(resource, **combined_args)
  File "/usr/lib/python2.6/site-packages/eve/methods/get.py", line 101, in get
    cursor = app.data.find(resource, req, lookup)
  File "/usr/lib/python2.6/site-packages/eve_sqlalchemy/__init__.py", line 123, in find
    spec = json.loads(req.where)
  File "/usr/lib64/python2.6/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.6/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
'''

**Comment by nicolaiarocci** [comment]
Eve-SQLAlchemy is not supported in this repo. Please open a ticket over there.
