### ISSUE TITLE
VERSIONING with item_lookup_field causes KeyError

### ISSUE THREAD

**Issue by otibsa** [pyeve/eve#524]
When using `VERSIONING=True` and `'item_lookup_field': 'lastname'`, I cannot GET a specific version of my endpoint:

`GET .../people/obama` works, but `...people/obama?version=1` creates the following error:

```
Traceback (most recent call last):
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/endpoints.py", line 90, in item_endpoint
    response = getitem(resource, **lookup)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 237, in rate_limited
    return f(*args, **kwargs)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/auth.py", line 60, in decorated
    return f(*args, **kwargs)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 782, in decorated
    r = f(resource, **combined_args)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/get.py", line 210, in getitem
    resource, req, lookup, document, version)
  File "/foobar/eve0.5_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/versioning.py", line 257, in get_old_document
    lookup[versioned_id_field()] = lookup[app.config['ID_FIELD']]
KeyError: '_id'
```

Can versioning be supported for these non-standard endpoints?

**Comment by otibsa** [comment]
I am currently working on this and I have a question:

When inserting a versioned document into the `people_versions`-collection, a new field is created: `_id_document`.

With `item_lookup_field` set to `lastname`, should this new field 
- contain the value of `lastname`?
- be called `lastname_document` instead?
- not be created at all?

**Comment by joshvillbrandt** [comment]
You definitely should not touch the `_id_document` field just because you want to use a different parameter to retrieve the data. The `_id_document` field is required to maintain the identity of the document, since the `_id` field in this context is a nearly useless identifier.

I'd have to look at how `item_lookup_field` is implemented. If this is creating an index, then I think most indexes would cache data somewhere outside of the document if at all. If this isn't creating an index, I don't think you should be modifying the data at all.

**Comment by joshvillbrandt** [comment]
@nicolaiarocci, when `item_lookup_field` is enabled without document versioning, do you store the data differently?

**Comment by nicolaiarocci** [comment]
Not at all. It only influences how items are retrieved.
