### ISSUE TITLE
Issue with embeddable at the level of nesting > 2

### ISSUE THREAD

**Issue by dimagogen** [pyeve/eve#856]
Hi, thank you for this project!

I have got an issue with using of embeddable at the level of nesting more then 2. Bellow is the example of the data, schemas and Traceback of the error. Appriciate your help with solving it 

Example:

```
{ 
    "_id" : ObjectId("00000000000000000000000"), 
    "hostname" : "TestHost", 
    "dispatchers" : [
        {
            "name" : "Test1", 
            "active" : true, 
            "classifiers" : [
                {
                    "cid" : "Logo", 
                    "root_topics" : [
                        ObjectId("00000000000000000000000")
                    ]
                }
            ], 
            "media_types" : [
                NumberInt(2)
            ], 
            "date_filters" : [
               {
                    "operation" : "lt", 
                    "date" : ISODate("2016-04-21T00:00:00.000+0000")
                }, 
                {
                    "operation" : "gt", 
                    "date" : ISODate("2016-04-14T00:00:00.000+0000")
                }
            ], 
            "required_labels" : [
                   ObjectId("00000000000000000000000")
            ], 
            "platforms" : {
                "operation" : "nin", 
                "platforms" : [
                    ObjectId("00000000000000000000000")
                ]
            }
        }
```

Schema:

```
{
    'hostname': {
        'type': 'string',
        'minlength': 2,
        'required': True,
    },
    'dispatchers': {
        'type': 'list',
        'schema': {
            'type': 'dict',
            'schema': {
                'name': {
                    'type': 'string',
                    'default': 'default',
                    'minlength': 2,
                    'required': True,
                },
                'active': {
                    'type': 'boolean',
                    'default': False
                },
                'classifiers': {
                    'type': 'list',
                    'schema': {
                        'type': 'dict',
                        'schema': {
                            'cid': {
                                'type': 'string',
                                'data_relation': {
                                    'resource': 'classifiers',
                                    'field': '_id',
                                    'embeddable': True
                                }
                            },
                            'root_topics': {
                                'type': 'list',
                                'schema': {
                                    'type': 'objectid',
                                    'data_relation': {
                                        'resource': 'topics',
                                        'field': '_id',
                                        'embeddable': True
                                    }
                                }
                            }
                        }
                    }
                },
                'media_types': {
                    'type': 'list',
                    'default': [1,2],
                    'schema': {
                        'type': 'integer',
                    }
                },
                'date_filters': {
                    'type': 'list',
                    'default': [],
                    'schema': {
                        'type': 'dict',
                        'schema': {
                            'operation': {
                                'type': 'string',
                                'minlength': 2,
                                'maxlength': 3,
                            },
                            'date': {
                                'type': 'datetime',
                            }
                        }
                    }
                },
                'required_labels': {
                    'type': 'list',
                    'default': [],
                    'schema': {
                        'type': 'objectid',
                        'data_relation': {
                            'resource': 'labels',
                            'field': '_id',
                            'embeddable': True
                        }
                    }
                },
                'platforms': {
                    'type': 'dict',
                    'schema': {
                        'platforms': {
                            'type': 'list',
                            'default': [],
                            'schema': {
                                'type': 'objectid',
                                'data_relation': {
                                    'resource': 'platforms',
                                    'field': '_id',
                                    'embeddable': True
                                }
                            }
                        },
                        'operation': {
                            'type': 'string',
                            'minlength': 2,
                            'maxlength': 3,
                        }
                    }
                }
            }
        }
    }
}
```

If we call (send request) to one of these requests(or all of them)  
1)  /request?embedded={"dispatchers.platforms.platforms":1}
2) /request?embedded={"dispatchers.classifiers.cid":1}
3) /request?embedded={"dispatchers.classifiers.root_topics":1}

We got an error: 

```
Traceback (most recent call last):
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/flaskapp.py", line 946, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/endpoints.py", line 54, in collections_endpoint
    response = get(resource, lookup)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/methods/common.py", line 242, in rate_limited
    return f(*args, **kwargs)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/auth.py", line 79, in decorated
    return f(*args, **kwargs)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/methods/common.py", line 944, in decorated
    r = f(resource, **combined_args)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/methods/get.py", line 105, in get
    build_response_document(document, resource, embedded_fields)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/methods/common.py", line 522, in build_response_document
    resolve_embedded_documents(document, resource, embedded_fields)
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/methods/common.py", line 716, in resolve_embedded_documents
    for subdocument in subdocuments(fields_chain[:-1], resource, document):
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/methods/common.py", line 672, in subdocuments
    for result in subdocuments(fields_chain[1:], resource, doc):
  File "/home/user/Projects/Environments/Backend/lib/python2.7/site-packages/eve/methods/common.py", line 667, in subdocuments
    resource, fields_chain[0])['data_relation']['resource']
TypeError: 'NoneType' object has no attribute '__getitem__'

```

Could you please advise on how to solve this problem?
I have added handling TypeError into the function common.py/subdocuments, but if it is right solution?

**Comment by romanga** [comment]
should 'dispatchers.classifiers.cid' type be objectid?

**Comment by dimagogen** [comment]
> should 'dispatchers.classifiers.cid' type be objectid?

No, string field

Example (Table):
```
{ 
    "_id" : "face_detector"
}
{ 
    "_id" : "face_classifier"
}
{ 
    "_id" : "badge_classifier"
}
```
