### ISSUE TITLE
Error when using unique_to_user value inside list of dicts schema

### ISSUE THREAD

**Issue by gwainer** [pyeve/eve#857]
I am trying to use a schema as the example below. I removed some irrelevant parts. It has some fields, and a list of `dependents`. Inside the `dependents`, each item is a dict and I've added `unique_to_user` property to the `code` key. 

```
employee_schema = {
    'some_field': {
    'type': 'string',
    'unique_to_user': True
    },
    'dependents': {
        'type': 'list',
        'schema': {
            'type': 'dict',
            'schema': {
                'name': {'type': 'string', 'required': True},
                'code': {
                    'type': 'string',
                    'regex': '\d{11}',
                    'unique_to_user': True
                },
            }
        }
    }
}
```

With this `unique_to_user` in place, whenever I try to `POST`or `PATCH` data with the `code` field, the response is **400 Bad Request**, and the following error stack

```
Traceback (most recent call last):
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/eve/methods/post.py", line 189, in post_internal
    validation = validator.validate(document)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 236, in validate
    return self._validate(document, schema, update=update, context=context)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 341, in _validate_definition
    definition.get('allow_unknown'))
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 595, in _validate_schema
    validator.validate({i: value[i]}, context=self.document)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 236, in validate
    return self._validate(document, schema, update=update, context=context)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 341, in _validate_definition
    definition.get('allow_unknown'))
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 607, in _validate_schema
    update=self.update)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 236, in validate
    return self._validate(document, schema, update=update, context=context)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/cerberus/cerberus.py", line 349, in _validate_definition
    validator(definition[rule], field, value)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/eve/io/mongo/validation.py", line 127, in _validate_unique_to_user
    auth_field, auth_value = auth_field_and_value(self.resource)
  File "/Users/gabrielcw/.virtualenvs/tiquetaque-api-env/lib/python3.5/site-packages/eve/auth.py", line 267, in auth_field_and_value
    resource_dict = app.config['DOMAIN'][resource]
KeyError

```

I will debug the code to see if I find something.

Thank You.

**Comment by srjpfc** [comment]
hello,

i'm having a problem similar to that one.

in a schema like this:
![screen shot 2017-06-16 at 01 34 10](https://user-images.githubusercontent.com/19504215/27207093-f27b012c-5233-11e7-95aa-6d11b760499f.png)

if i have unique: True in 'field_name', i get the same error:

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/eve/methods/post.py", line 193, in post_internal
    validation = validator.validate(document)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 236, in validate
    return self._validate(document, schema, update=update, context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 341, in _validate_definition
    definition.get('allow_unknown'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 595, in _validate_schema
    validator.validate({i: value[i]}, context=self.document)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 236, in validate
    return self._validate(document, schema, update=update, context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 341, in _validate_definition
    definition.get('allow_unknown'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 607, in _validate_schema
    update=self.update)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 236, in validate
    return self._validate(document, schema, update=update, context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cerberus/cerberus.py", line 349, in _validate_definition
    validator(definition[rule], field, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/eve/io/mongo/validation.py", line 145, in _validate_unique
    self._is_value_unique(unique, field, value, {})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/eve/io/mongo/validation.py", line 158, in _is_value_unique
    resource_config = config.DOMAIN[self.resource]
KeyError: None

with status 400.

is there a workaround?

thank you

**Comment by vishnuvp** [comment]
Hi , i too have a similar kind of issue. 
My schema looks something like this 
users_schema = {
'from_attributes':{
    	'type' : 'list',
    	'schema':{
            'type':'dict',
            'schema': {
            	'name': {'type':'string'},
                'value': {'type': ['string','integer']},
                'isNotify' : {'type':'boolean'},
                'UID' : {'type':'string',
                		'required':True,
                		'unique' : True,
                		
                		}
                      },
        },
     },
}

its having a unique field  set to true in the list of dicts. When i try to do a post, i get the following error stack: 
--------------------------------------------------------------------------------
ERROR in post [/usr/lib/python3.5/site-packages/eve/methods/post.py:219]:

--------------------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/lib/python3.5/site-packages/eve/methods/post.py", line 193, in post_internal
 validation = validator.validate(document)
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 236, in validate
 return self._validate(document, schema, update=update, context=context)
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 282, in _validate
 self._validate_definition(definition, field, value)
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 341, in _validate_definition
 definition.get('allow_unknown'))
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 595, in _validate_schema
 validator.validate({i: value[i]}, context=self.document)
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 236, in validate
 return self._validate(document, schema, update=update, context=context)
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 282, in _validate
 self._validate_definition(definition, field, value)
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 341, in _validate_definition
 definition.get('allow_unknown'))
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 607, in _validate_schema
 update=self.update)
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 236, in validate
 return self._validate(document, schema, update=update, context=context)
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 282, in _validate
 self._validate_definition(definition, field, value)
File "/usr/lib/python3.5/site-packages/cerberus/cerberus.py", line 349, in _validate_definition
 validator(definition[rule], field, value)
File "/usr/lib/python3.5/site-packages/eve/io/mongo/validation.py", line 145, in _validate_unique
 self._is_value_unique(unique, field, value, {})
File "/usr/lib/python3.5/site-packages/eve/io/mongo/validation.py", line 158, in _is_value_unique
 resource_config = config.DOMAIN[self.resource]
 KeyError


Is there a workaround for it?

**Comment by nicolaiarocci** [comment]
@vishnuvp I tested your setup and it does not crash on my side. Are you sure the endpoint is properly configured:

    users_schema = {
        'from_attributes': {
            'type' : 'list',
                'schema': {
                    'type':'dict',
                    'schema': {
                        'name': {'type':'string'},
                        'value': {'type': ['string','integer']},
                        'isNotify' : {'type':'boolean'},
                        'UID' : {'type':'string', 'required':True, 'unique': True, }
                    }}}}

   DOMAIN = {
        'users': {
            'schema': users_schema
        }}

With this being said, currently `unique` is not supported within lists, so while it will work with no crash,  your unique rule will be ignored.
