### ISSUE TITLE
Filtering multiple fields results in EveWSGIRequestHandler

### ISSUE THREAD

**Issue by hroncok** [pyeve/eve#859]
This is what happens, when I try to filter by multiple fields:

```
GET /courses/?where={"teacher":2, "day":1}
```

```
Exception happened during processing of request from ('127.0.0.1', 46842)
Traceback (most recent call last):
  File "/usr/lib64/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "utvsapi-eve/venv/lib64/python3.4/site-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib64/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "utvsapi-eve/venv/lib64/python3.4/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    elif self.parse_request():
  File "/usr/lib64/python3.4/http/server.py", line 314, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib64/python3.4/http/server.py", line 428, in send_error
    self.log_error("code %d, message %s", code, message)
  File "utvsapi-eve/venv/lib64/python3.4/site-packages/werkzeug/serving.py", line 273, in log_error
    self.log('error', *args)
  File "utvsapi-eve/venv/lib64/python3.4/site-packages/werkzeug/serving.py", line 279, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "utvsapi-eve/venv/lib64/python3.4/site-packages/werkzeug/serving.py", line 267, in address_string
    return self.environ['REMOTE_ADDR']
AttributeError: 'EveWSGIRequestHandler' object has no attribute 'environ'
```

Both individual queries work fine:

```
GET /courses/?where={"teacher":2}
GET /courses/?where={"day":1}
```

Is filtering on multiple fields supposed to work or not? If not, server should reply with 400 error, right?

**Comment by nicolaiarocci** [comment]
It should work. The error you are getting is weird... seems related to some config/install issue. On which Eve version are you?

**Comment by nicolaiarocci** [comment]
PS: `http://eve-demo.herokuapp.com/people?where={"lastname": "Doe", "firstname": "John"}` works, if you want to try it out.

**Comment by hroncok** [comment]
0.6.3

I use https://github.com/RedTurtle/eve-sqlalchemy that might be relevant.

**Comment by hroncok** [comment]
`self.environ['REMOTE_ADDR']` seems like a config thing, but I don't understand why it's only being checked when `where` has multiple elements.

**Comment by hroncok** [comment]
Just to make sure, I'v opened https://github.com/RedTurtle/eve-sqlalchemy/issues/111 as well.
