### ISSUE TITLE
Minimal sample fails to run without MongoDB service

### ISSUE THREAD

**Issue by mloskot** [pyeve/eve#891]
I'm trying Eve 0.6.4 for the first time running the very minimal _people_ application sample from http://python-eve.org/quickstart.html, on Linux with Python 3.5.

I have not configured the sample to use MongoDB.
I have installed MongoDB on my Linux though.
I noticed strange failures.

Here is the sequnce of events outlined:
1. MongoDB service **started**.
Keep in mind, _I have not configured any connection_ in `settings.py` or anywhere for the app, so the service is not supposed to be used.
2. `curl http://127.0.0.1:5000` succeeds with 200
3. `curl http://127.0.0.1:5000/people` succeeds with 200
4. MongoDB service **stopped**.
5. `curl http://127.0.0.1:5000` succeeds with 200
6. `curl http://127.0.0.1:5000/people` fails with 500

Here is screenshot that shows all the steps in action:

![python-eve-minimal-fail-wo-mongodb](https://cloud.githubusercontent.com/assets/80741/17403023/43c6f77e-5a56-11e6-9b82-6b0adfd5ac97.png)

After turning the debugging on `app.run(debug=True)` and repeating the steps, traceback suggests that `GET` request at `/people` endpoint tries to hit MongoDB:

```
127.0.0.1 - - [04/Aug/2016 14:11:34] "GET /people HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/eve/flaskapp.py", line 968, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/eve/endpoints.py", line 54, in collections_endpoint
    response = get(resource, lookup)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/eve/methods/common.py", line 242, in rate_limited
    return f(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/eve/auth.py", line 79, in decorated
    return f(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/eve/methods/common.py", line 949, in decorated
    r = f(resource, **combined_args)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/eve/methods/get.py", line 104, in get
    for document in cursor:
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/pymongo/cursor.py", line 1012, in _refresh
    self.__read_concern))
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/pymongo/cursor.py", line 850, in __send_message
    **kwargs)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/pymongo/mongo_client.py", line 827, in _send_message_with_response
    server = topology.select_server(selector)
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/pymongo/topology.py", line 210, in select_server
    address))
  File "/home/vagrant/.virtualenvs/eve/lib/python3.5/site-packages/pymongo/topology.py", line 186, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

Although the [Quickstart](http://python-eve.org/quickstart.html#a-minimal-application) clearly indicates no database is requied:

> Since we didn’t provide any database detail in settings.py, Eve (...) seamlessly serves an empty resource, as we don’t want to let API users down.

the [Eve is Simple](http://python-eve.org/index.html) on the frontpage says:

> All you need to bring your API online is a database

Language of the prose documentation does not have to be precise, but the failures I'm experiencing make me think that MongoDB might be required.

Initially, I encountered the problem on PythonAnywhere with Python 3.5 (see [how I installed Eve on PA](https://www.pythonanywhere.com/forums/topic/3730/#id_post_33244)).
Then, I also reproduced exactly the same problem on Linux running locally.

**Comment by nicolaiarocci** [comment]
Yes, that's pymongo failing when trying to select a valid server. If you look at the quick start [prerequisites](http://python-eve.org/quickstart.html#quickstart) though, you will find that a MongoDB instance must, in fact, be running.

If this is a potential point of friction we could consider merging "Minimal Application" and "Database Interlude" sections, since using Eve without a data backend makes no sense. On the other hand,  the purpose of "Minimal Application" is simply to get the user accustomed with Eve basics. Thoughts?

**Comment by mloskot** [comment]
Yes, the prerequisites are clear. I just noticed the issue with this line:

> Since we didn’t provide any database detail in settings.py, Eve (...) seamlessly serves an empty resource, as we don’t want to let API users down.

which does or might suggest, running database is not required until to that point, until getting into the "Database Interlude" part.

Perhaps I misinterpreted the section and it is not an issue for others, so no need to change.

Thanks for clarification.

**Comment by ydaniels** [comment]
Just faced the issue, i think that side has to be written again

**Comment by ggstuart** [comment]
#### I'd say the (otherwise excellent) guide is broken. 
I hit this issue on my first attempt with using eve. The guide clearly implies that the request to /people should work. 

> Since we didn’t provide any database detail in settings.py, Eve has no clue about the real content of the people collection (it might even be non-existent) and seamlessly serves an empty resource, as we don’t want to let API users down.

Options:
- the guide needs to be tweaked
- eve should return empty arrays by default when no database is configured (with a suitable warning level log message perhaps). 

The implication of the guide and my expectation when getting started was that I didn't need to handle databases yet. It looked very bad to me until I found this thread describing it as a potential documentation issue.

**Comment by nicolaiarocci** [comment]
Let's tweak the docs. Anyone up for a PR?
