### ISSUE TITLE
PATCH with custom '_id' field name causes exception

### ISSUE THREAD

**Issue by pedro2555** [pyeve/eve#941]
If you define a custom name for setting ID_FIELD, patch operations will crash the server with the following stacktrace:

```
Traceback (most recent call last):
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/eve/flaskapp.py", line 968, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/eve/endpoints.py", line 94, in item_endpoint
    response = patch(resource, **lookup)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/eve/methods/common.py", line 242, in rate_limited
    return f(*args, **kwargs)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/eve/auth.py", line 79, in decorated
    return f(*args, **kwargs)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/eve/methods/common.py", line 949, in decorated
    r = f(resource, **combined_args)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/eve/methods/patch.py", line 41, in patch
    skip_validation=False, **lookup)
  File "/home/prodrigues/still-sands-21077/lib/python3.5/site-packages/eve/methods/patch.py", line 143, in patch_internal
    object_id = original[resource_def['id_field']]
```

**Comment by pedro2555** [comment]
@pedro2555 needs tests

**Comment by nicolaiarocci** [comment]
I cannot reproduce this. I went to the settings, changed `ID_FIELD` to a different field name, then performed a POST and a PATCH on the posted document with no error. Do you have more details to help me reproduce it?
