### ISSUE TITLE
EveWSGIRequestHandler when GETting from https while server listens to http

### ISSUE THREAD

**Issue by gmargari** [pyeve/eve#980]
It's not actually a bug since the server is listening only to http and the client requests for https. No web server such as apache/nginx is running that handles/redirects https.

But I was getting these exceptions on my log and could not understand what's wrong. Until I talked with the client and he told me that he was trying to access using https.

```python
# server.py
from eve import Eve
app = Eve(settings={'DOMAIN': {}})
app.run(debug=True)
```

Server:
```bash
# Git-cloned latest Eve version (as of 6/2/2017)
> python3 server.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 237-912-371
```

Client (error is expected):
```bash
> wget https://127.0.0.1:5000
--2017-02-06 13:30:06--  https://127.0.0.1:5000/
Connecting to 127.0.0.1:5000... connected.
Unable to establish SSL connection.
```

Server:
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 34104)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 251, in handle_one_request
    elif self.parse_request():
  File "/usr/lib/python3.5/http/server.py", line 327, in parse_request
    "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python3.5/http/server.py", line 452, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 273, in log_error
    self.log('error', *args)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 279, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 267, in address_string
    return self.environ['REMOTE_ADDR']
AttributeError: 'EveWSGIRequestHandler' object has no attribute 'environ'
----------------------------------------
```

**Comment by gmargari** [comment]
With python2.7 I get the following in case the client GETs https://127.0.0.1:5000:

```bash
> python2.7 server.py 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 158-672-419
127.0.0.1 - - [06/Feb/2017 14:36:40] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\xbc\x01\x00\x00\xb8\x03\x03A\xfd%\xe8T\x80\xdc_\x04\x17\xa7\xacV\\\xcc\x1e|\xa9J\x88\xfe0\xd1H\xd5\x02\x05\xba\x1dA\xf9\xa2\x00\x00$JJ\xc0+\xc0/\xc0,\xc00\xcc\xa9\xcc\xa8\xcc\x14\xcc\x13\xc0')
127.0.0.1 - - [06/Feb/2017 14:36:40] "��A�%�T��_��V\�|�J��0�H��A��$JJ�+�/�,�0̨̩���	��" 400 -
```

Also, don't know if 859 is related because I found there the same error.
