### ISSUE TITLE
AttributeErrors on defaults.py 

### ISSUE THREAD

**Issue by jbool24** [pyeve/eve#983]
AttributeError occurs when testing basic app from quickstart guide using all defaults.

**Using:** 
virtualenv 15.1.0
Eve v0.7
Python3.5
```
from eve import Eve
app = Eve()
if __name__ =='__main__':
    app.run(debug=True)
```

The following is the Traceback

```Traceback (most recent call last):
  File "server.py", line 9, in <module>
    app = Eve()
  File "/mnt/c/Users/Justin/CodeProjects/fabric_management/unix_env/lib/python3.4/site-packages/eve/flaskapp.py", line 176, in __init__
    self.register_resource(resource, settings)
  File "/mnt/c/Users/Justin/CodeProjects/fabric_management/unix_env/lib/python3.4/site-packages/eve/flaskapp.py", line 891, in register_resource
    self._set_resource_defaults(resource, settings)
  File "/mnt/c/Users/Justin/CodeProjects/fabric_management/unix_env/lib/python3.4/site-packages/eve/flaskapp.py", line 626, in _set_resource_defaults
    settings['defaults'] = build_defaults(schema)
  File "/mnt/c/Users/Justin/CodeProjects/fabric_management/unix_env/lib/python3.4/site-packages/eve/defaults.py", line 47, in build_defaults
    elif value.get('type') == 'dict' and 'schema' in value:
AttributeError: 'str' object has no attribute 'get'```

**Comment by nicolaiarocci** [comment]
Just tried this with Python 3.5 and Eve 0.7 with no issues. Virtualenv is 13.something, but I doubt it matters. Will try to reproduce this again tomorrow. Anyone else having this?

**Comment by jbool24** [comment]
I just tried again because I noticed my virtualenv was actually using python3.4. This time I was also on a linux machine (the previous attempt was on Windows 10) and using python3.5 and I get the same trace int default.py. When I create the app interactively in python terminal I can successfully instantiate and run a Flask app but not an Eve app.
```
from flask import Flask
app = Flask("someName")
app.run() //This works and runs the dev server

from eve import Eve
app = Eve()
app.run() // This does not work and I get the same trackback as posted above.
```
'value' is a type 'str' and has no attribute 'get'

**Comment by nicolaiarocci** [comment]
Can you please also post your settings.py contents?

**Comment by jbool24** [comment]
Sorry for the delay. Here is the code in my settings.py. I used mostly settings.py from the [demo](https://github.com/nicolaiarocci/eve-demo) as a basis. 

```python
import os

from schemas.productions import Productions

# We want to seamlessy run our API both locally and on Heroku. If running on
# Heroku, sensible DB connection settings are stored in environment variables.
MONGO_HOST = os.environ.get('MONGO_HOST', '127.0.0.1')
MONGO_PORT = os.environ.get('MONGO_PORT', 27017)
MONGO_DBNAME = os.environ.get('MONGO_DBNAME', 'fab_operations')


# Enable reads (GET), inserts (POST) and DELETE for resources/collections
# (if you omit this line, the API will default to ['GET'] and provide
# read-only access to the endpoint).
RESOURCE_METHODS = ['GET', 'POST', 'DELETE']

# Enable reads (GET), edits (PATCH) and deletes of individual items
# (defaults to read-only item access).
ITEM_METHODS = ['GET', 'PATCH', 'DELETE']

# We enable standard client cache directives for all resources exposed by the
# API. We can always override these global settings later.
CACHE_CONTROL = 'max-age=20'
CACHE_EXPIRES = 20


# The DOMAIN dict explains which resources will be available and how they will
# be accessible to the API consumer.
DOMAIN = {
     'productions': Productions,
    
}
```
